// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (symbol, name, asset_type)
VALUES ($1, $2, $3)
RETURNING id, symbol, name, asset_type, created_at
`

type CreateAssetParams struct {
	Symbol    string      `json:"symbol"`
	Name      pgtype.Text `json:"name"`
	AssetType string      `json:"asset_type"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset, arg.Symbol, arg.Name, arg.AssetType)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Name,
		&i.AssetType,
		&i.CreatedAt,
	)
	return i, err
}

const getAssetBySymbol = `-- name: GetAssetBySymbol :one
SELECT id, symbol, name, asset_type, created_at
FROM assets
WHERE symbol = $1 AND asset_type = $2
`

type GetAssetBySymbolParams struct {
	Symbol    string `json:"symbol"`
	AssetType string `json:"asset_type"`
}

func (q *Queries) GetAssetBySymbol(ctx context.Context, arg GetAssetBySymbolParams) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetBySymbol, arg.Symbol, arg.AssetType)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Name,
		&i.AssetType,
		&i.CreatedAt,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
SELECT id, symbol, name, asset_type, created_at
FROM assets
ORDER BY symbol
`

func (q *Queries) ListAssets(ctx context.Context) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Name,
			&i.AssetType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
