// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assets.sql

package db

import (
	"context"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (symbol, name, asset_type)
VALUES ($1, $2, $3)
RETURNING id, symbol, name, asset_type, created_at
`

type CreateAssetParams struct {
	Symbol    string  `json:"symbol"`
	Name      *string `json:"name"`
	AssetType string  `json:"asset_type"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset, arg.Symbol, arg.Name, arg.AssetType)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Name,
		&i.AssetType,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAsset = `-- name: DeleteAsset :exec
DELETE FROM assets
WHERE id = $1
`

func (q *Queries) DeleteAsset(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAsset, id)
	return err
}

const getAssetByID = `-- name: GetAssetByID :one
SELECT id, symbol, name, asset_type, created_at
FROM assets
WHERE id = $1
`

func (q *Queries) GetAssetByID(ctx context.Context, id int64) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByID, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Name,
		&i.AssetType,
		&i.CreatedAt,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
SELECT id, symbol, name, asset_type, created_at
FROM assets
ORDER BY id
`

func (q *Queries) ListAssets(ctx context.Context) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Name,
			&i.AssetType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAsset = `-- name: UpdateAsset :one
UPDATE assets
SET
  symbol = $2,
  name = $3,
  asset_type = $4
WHERE id = $1
RETURNING id, symbol, name, asset_type, created_at
`

type UpdateAssetParams struct {
	ID        int64   `json:"id"`
	Symbol    string  `json:"symbol"`
	Name      *string `json:"name"`
	AssetType string  `json:"asset_type"`
}

func (q *Queries) UpdateAsset(ctx context.Context, arg UpdateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, updateAsset,
		arg.ID,
		arg.Symbol,
		arg.Name,
		arg.AssetType,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Name,
		&i.AssetType,
		&i.CreatedAt,
	)
	return i, err
}
