// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Asset struct {
	ID        int64              `json:"id"`
	Symbol    string             `json:"symbol"`
	Name      *string            `json:"name"`
	AssetType string             `json:"asset_type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PriceSnapshot struct {
	ID         int64              `json:"id"`
	AssetID    int64              `json:"asset_id"`
	Price      pgtype.Numeric     `json:"price"`
	CapturedAt pgtype.Timestamptz `json:"captured_at"`
}

type Transaction struct {
	ID          int64              `json:"id"`
	AssetID     int64              `json:"asset_id"`
	TxType      string             `json:"tx_type"`
	Quantity    pgtype.Numeric     `json:"quantity"`
	Price       pgtype.Numeric     `json:"price"`
	Fee         pgtype.Numeric     `json:"fee"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	CorrectedBy *int64             `json:"corrected_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
