// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: portfolio.sql

package db

import (
	"context"
)

const getNetQuantityByAsset = `-- name: GetNetQuantityByAsset :many
SELECT
    asset_id,
    SUM(
        CASE
            WHEN tx_type IN ('buy', 'transfer_in') THEN quantity
            WHEN tx_type IN ('sell', 'transfer_out') THEN -quantity
        END
    ) AS net_quantity
FROM transactions
GROUP BY asset_id
`

type GetNetQuantityByAssetRow struct {
	AssetID     int64 `json:"asset_id"`
	NetQuantity int64 `json:"net_quantity"`
}

func (q *Queries) GetNetQuantityByAsset(ctx context.Context) ([]GetNetQuantityByAssetRow, error) {
	rows, err := q.db.Query(ctx, getNetQuantityByAsset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNetQuantityByAssetRow
	for rows.Next() {
		var i GetNetQuantityByAssetRow
		if err := rows.Scan(&i.AssetID, &i.NetQuantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
