// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestPrice = `-- name: GetLatestPrice :one
SELECT id, asset_id, price, captured_at
FROM price_snapshots
WHERE asset_id = $1
ORDER BY captured_at DESC
LIMIT 1
`

func (q *Queries) GetLatestPrice(ctx context.Context, assetID int64) (PriceSnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestPrice, assetID)
	var i PriceSnapshot
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.Price,
		&i.CapturedAt,
	)
	return i, err
}

const upsertPriceSnapshot = `-- name: UpsertPriceSnapshot :one
INSERT INTO price_snapshots (asset_id, price, captured_at)
VALUES ($1, $2, $3)
ON CONFLICT (asset_id, captured_at)
DO UPDATE SET price = EXCLUDED.price
RETURNING id, asset_id, price, captured_at
`

type UpsertPriceSnapshotParams struct {
	AssetID    int64              `json:"asset_id"`
	Price      pgtype.Numeric     `json:"price"`
	CapturedAt pgtype.Timestamptz `json:"captured_at"`
}

func (q *Queries) UpsertPriceSnapshot(ctx context.Context, arg UpsertPriceSnapshotParams) (PriceSnapshot, error) {
	row := q.db.QueryRow(ctx, upsertPriceSnapshot, arg.AssetID, arg.Price, arg.CapturedAt)
	var i PriceSnapshot
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.Price,
		&i.CapturedAt,
	)
	return i, err
}
