// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	GetAssetBySymbol(ctx context.Context, arg GetAssetBySymbolParams) (Asset, error)
	GetLatestPrice(ctx context.Context, assetID int64) (PriceSnapshot, error)
	GetNetQuantityByAsset(ctx context.Context) ([]GetNetQuantityByAssetRow, error)
	ListAllTransactions(ctx context.Context) ([]Transaction, error)
	ListAssets(ctx context.Context) ([]Asset, error)
	ListTransactionsByAsset(ctx context.Context, assetID int64) ([]Transaction, error)
	UpsertPriceSnapshot(ctx context.Context, arg UpsertPriceSnapshotParams) (PriceSnapshot, error)
}

var _ Querier = (*Queries)(nil)
