// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    asset_id, tx_type, quantity, price, fee, occurred_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, asset_id, tx_type, quantity, price, fee, occurred_at, created_at
`

type CreateTransactionParams struct {
	AssetID    int64              `json:"asset_id"`
	TxType     string             `json:"tx_type"`
	Quantity   pgtype.Numeric     `json:"quantity"`
	Price      pgtype.Numeric     `json:"price"`
	Fee        pgtype.Numeric     `json:"fee"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.AssetID,
		arg.TxType,
		arg.Quantity,
		arg.Price,
		arg.Fee,
		arg.OccurredAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.TxType,
		&i.Quantity,
		&i.Price,
		&i.Fee,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAllTransactions = `-- name: ListAllTransactions :many
SELECT id, asset_id, tx_type, quantity, price, fee, occurred_at, created_at
FROM transactions
ORDER BY occurred_at ASC
`

func (q *Queries) ListAllTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listAllTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.TxType,
			&i.Quantity,
			&i.Price,
			&i.Fee,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAsset = `-- name: ListTransactionsByAsset :many
SELECT id, asset_id, tx_type, quantity, price, fee, occurred_at, created_at
FROM transactions
WHERE asset_id = $1
ORDER BY occurred_at ASC
`

func (q *Queries) ListTransactionsByAsset(ctx context.Context, assetID int64) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByAsset, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.TxType,
			&i.Quantity,
			&i.Price,
			&i.Fee,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
